[project]
name = 'contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.MCrowdFundingCollective]
path = 'contracts/MCrowdFundingCollective.clar'
clarity_version = 2
epoch = 2.4

[contracts.Pot]
path = 'contracts/Pot.clar'
clarity_version = 2
epoch = 2.4

[contracts.Request]
path = 'contracts/Request.clar'
clarity_version = 2
epoch = 2.4

[contracts.User]
path = 'contracts/User.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
